apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica-set-1
  template:
    metadata:
      labels:
        app: replica-set-1
    spec:
      containers:
      - name: busybox
        image: busybox
